---
hosts: localhost
connection: local
tasks:
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "public-compute-instance"
    key_name: "prod-ssh-key"
    vpc_subnet_id: subnet-036e5b66c48748775
    instance_type: t2.micro
    security_group: default
    network_interfaces:
      - assign_public_ip: true
    image_id: ami-0dee22c13ea7a9a67
    tags:
      Environment: Testing
